baseURL: "https://sierrab1.github.io/"
languageCode: "en-us"
title: "Sierra Barkdoll"
theme: "creative"
params:
  profile: "/me_lowres.jpg?raw=true" # your photo (or logo) here
  style: sea
  description: Describe your website
  copyright: '&copy;2020 Sierra Barkdoll'
  sidebarAbout:
    - Geography and Environmental Systems, B.S.
    - Biology Minor
    - GIS Certificate
    - University of Maryland, Baltimore County

  email: sierrabarkdoll@yahoo.com
  navlinks:
    - name: Portfolio
      url: projects/
      home: true
    - name: About
      url: about/
  social:
    email: sierrabarkdoll@yahoo.com
    linkedin: https://www.linkedin.com/in/sierra-barkdoll-14b6abab
    github: https://github.com/sierrab1
    whatsapp: https://wa.me/14104582721
